-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th4 07, 2019 lúc 04:11 PM
-- Phiên bản máy phục vụ: 10.1.38-MariaDB
-- Phiên bản PHP: 7.3.2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `truyen`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `doctruyen`
--

CREATE TABLE `doctruyen` (
  `id_truyen` int(11) NOT NULL,
  `tenTruyen` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tacGia` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL,
  `theLoai` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `noiDung` varchar(10000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hinhAnh` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `anhBia` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_trangthai` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `doctruyen`
--

INSERT INTO `doctruyen` (`id_truyen`, `tenTruyen`, `tacGia`, `theLoai`, `noiDung`, `hinhAnh`, `anhBia`, `id_trangthai`) VALUES
(1, 'ĐẠO CHU', 'DanteSparda', 'Ngôn tình', 'Tác giả sáng tác câu chuyện này theo  thể loại đồng nhân trọng sinh xuyên không nhân vật lần lượt qua các truyện.Ở mỗi thế giới thì nhân vật phải bắt đầu lại từ đầu và phải tuân thủ theo quy tắc thế giới ấy. Nhân vật chính đi theo con đường đáp ứng mong ước của thiên đạo. Hoàn thành giao dịch cùng thiên đạo đạt được một phần căn nguyên.\r\n\r\n(Không hệ thống lưu, xuyên qua nhiều thế giới, có bàn tay vàng nhưng không phải rất mạnh. Nhân vật chính mất gần hết ký ức nên không biết trước. Coi như đọc hoàn toàn mới đi. Mỗi thế giới đều đi đến hết truyện. Truyện có thêm tí sắc cho nó nóng nhé anh em. ', 'http://192.168.56.1:8080/doctruyen/anh/dao-chu.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia2.jpg', 1),
(2, 'THÚ TU THÀNH THẦN', 'cuuviho1687', 'Dị Giới, Xuyên Không', 'Nội dung chính của câu chuyện xoay quanh về cuộc đáu trí giằng co giữa  main và \"Hệ thống \" cũng từ đó tạo ra các tình huống dở khóc dở cười. Nhưng càng đi về cuối truyện thì \"Hệ thống\" sẽ càng nặng tay.\r\n\r\n\"Ta cho ngươi sức mạnh nhìn ngươi chiếm lấy thế giới tất cả tiền tài,mỹ nữ. Mạnh mẽ lên thanh niên,cùng chúng ta xé mở không gian đạp phá Thần giới.\"Hệ thống chi đạo\r\n', 'http://192.168.56.1:8080/doctruyen/anh/thu-tu-thanh-than.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 1),
(3, 'TỔNG GIÁM ĐỐC SIÊU CẤP', 'anhvodoi94', 'Ngôn Tình', 'Nam chính la được miêu tả có số phận vô cùng thê thảm một màu đen chính Dương Tuấn Vũ. Cuộc đời hắn khi vừa lên 8 tuổi thì cha mẹ gặp tai nạn xe hơi mất mạng, đến khi 12 tuổi thì bà ngoại cũng mất. Không chỉ vậy mà hắn đi xin việc thì luôn bị mất việc bởi những lý do \"chính đáng vớ vẩn\", đến khi được chỉ có tình yêu đi cùng với hắn. \r\n\r\nCứ nghĩ hắn còn chút niềm vui nhỏ nhưng không ngờ sau 8 năm thì người yêu cũng chắp cánh bay đi. Dương Tuấn Vũ chán nản và quyết định nhận lời một công việc chi nhánh Na Uy của ngân hàng A&B. Hắn lên máy bay và quyết vứt bỏ lại quá khứ để sống một cuộc sống mới. ', 'http://192.168.56.1:8080/doctruyen/anh/tong-giam-doc-sieu-cap.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia2.jpg', 1),
(4, 'SIÊU VIỆT NHỊ THỨ NGUYÊN', 'Phong Trần Lãng Tử', 'Dị Giới, Xuyên Không', 'Trong câu chuyện này tác giả không cho nam chính trọng sinh,cũng sẽ không có hệ thống, mà chỉ có dị năng!\r\n\r\nĐầu tiên mở ra một thế giới siêu anh hùng cùng tội phạm tràn ngập máu và nước mắt.\r\n\r\nNơi này có bi thương cùng chết chóc. Nhưng cũng là nơi tình bạn và công lý tỏa ánh sáng mãnh liệt!', 'http://192.168.56.1:8080/doctruyen/anh/sieu-viet-nhi-thu-nguyen.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 1),
(7, 'NÔ THÊ MUỐN XOAY NGƯỜI', 'Linh Khuê', 'Dị Giới, Xuyên Không, Dị Năng', 'Hoắc Duật Hy, tiểu thư lá ngọc cành vàng của tập đoàn Hắc thị.Lúc ấy, điều đầu tiên cô nghĩ đến đầu tiên rằng người đang nằm trên giường là một kẻ trai bao. Khi Duật Hy định rời bước thì anh ta bỗng nhiên kêu lên, còn tỏ vẻ hình như đã sốt rồi. Có lẽ không cầm lòng trước giọng nói yếu ớt như thế nên cô đã đem anh đi bệnh viện.\r\n\r\nTư Cảnh Hàn, ông trùm của tổ chức đặc công lớn nhất và còn là một tổng tài lạnh lùng, tàn khốc, luôn ở phía sau thao túng Tư thị.\r\n\r\nCô gặp anh vào tiệc sinh nhật của bạn, khi ấy bản thân bị lạc khi đi tìm chỗ vệ sinh, vô tình bước vào căn phòng có người đàn ông có đường nét còn xinh đẹp hơn phụ nữ.\r\n', 'http://192.168.56.1:8080/doctruyen/anh/t1.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 2),
(8, 'XIN HÃY ÔM EM', 'Bắc Chi', 'Tiên Hiệp, Ngôn Tình', 'Dường như đối với mỗi tín đồ ngôn tình chúng ta, motip truyện có xuất hiện hình tượng vị tổng giám đốc không những bá đạo mà còn lạnh lùng đã trở nên vô cùng quen thuộc rồi đúng không nhỉ? Câu chuyện tình đó cũng chỉ đơn giản xoay quanh hai nhân vật chính, tình tiết chính lặp đi lặp lại là những sự hiểu lầm, phát hiện ra chân tướng, rồi từ đó nhận ra trái tim của bản thân thực sự muốn gì.\r\n\r\nĐáng lẽ sau khi kết thúc tình một đêm phải là cảnh ai lo việc của người nấy, trở thành người dưng với nhau. Như thế là tốt lắm rồi!\r\nNhưng vì cái gì mà hắn cứ phải ép buộc cô ở bên cạnh. Thế nhưng biết sao được, vị tổng tài này lại có tính cách cuồng bá bẩm sinh như thế đó, cô biết làm sao bây giờ?\r\n\r\nChỉ sau một đêm cuồng nhiệt với hắn, cô tự cảm thấy bản thân mình vô cùng xui xẻo, ném lên giường hai trăm đồng sau đó ai oán rời đi. Tưởng rằng từ nay hai người đối với nhau chỉ là người dưng - mà mọi chuyện đáng lẽ phải như thế thật. Ai ngờ, cô liên tục bị hắn cho người đem ném lên giường…', 'http://192.168.56.1:8080/doctruyen/anh/xinhayomemA1mKTePmoS.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia3.jpg', 2),
(9, 'LÔI ĐỘNG CỬU THIÊN', 'Kháng Ngũ Hành', 'Dị Giới, Xuyên Không, Dị Năng', 'Trong một gian phòng ngăn nắp sáng ngời, một gã thiếu niên ước chừng mười lăm mười sáu tuổi đang lười biếng nằm ở trên giường, hai mắt vô thần nhìn lên trần nhà, khóe miệng mang theo một tia cười khổ bất đắc dĩ: \"Không nghĩ tới cũng có một ngày... ta xuyên việt!\"\r\n\r\nHắn tên là Hứa Phong, kiếp trước Hứa Phong là một gã sinh viên bình thường ở thế kỷ 21 trên địa cầu, cuồng tiểu thuyết tiên hiệp huyền ảo đến mức quên ăn quên ngủ, vì vậy thường xuyên sưu tầm một ít cái gọi là \"\"Tu chân bí tịch\", tưởng tượng có một ngày mình cũng có thể trở thành một vị đại năng có thể tay hái sao trời, chân đạp cửu thiên... bất quá tất cả \"bí tịch tu chân\" đều là hàng lởm.', 'http://192.168.56.1:8080/doctruyen/anh/loidongcuuthien8UtxW5Ml3Q.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 2),
(10, 'XUYÊN VỀ THỜI NGUYỄN HỖN QUÂN ', 'KennyNguyen', 'Dị Giới, Xuyên Không', 'Quang Diệu là một đặc vụ xuất sắc với nhiều chiến công tình báo lợi hại đã đưa về cho tổ quốc. Để làm được điều này hắn đã phải vào vai đủ loại nghề nghiệp để thâm nhập Cường quốc Phương bắc trên, từ sinh viên du học, đến thương nhân, công nhân ngay cả người vợ hắn cưới cũng là một nữ nhân quốc gia trên. Mặc dù tình cảm của hắn dành cho cô gái này có thể là một phần nào đó thật lòng nhưng nghĩa vụ quốc gia vẫn bày ra đấy vậy nên Quang Diệu hắn chưa bao giờ để cấp trên tại HN thất vọng bao giờ. \r\n\r\nNhưng vận may của hắn đến cùng cũng chấm dứt, hắn bị lộ thân phận rồi. Đáng lẽ ra hắn vẫn có cơ hội sống nếu đầu hàng và thành tù binh chính trị, nhưng thông tin về kế hoạch phá hoại của “địch nhân” quá nguy hiểm. Quang Diệu hắn phải báo về cho lãnh đạo tại HN bằng mọi giá. Tất nhiên hắn đã thành công gửi được thông tin kia về quốc gia nhưng cái giá phải trả cho việc chậm chễ vài giây đó là sinh mạng. Quang Diệu đã mãi mãi nằm xuống nơi đất khách quê người.', 'http://192.168.56.1:8080/doctruyen/anh/xuyenvethoinguyenhonquanphietSFWGeiq83D.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 2),
(11, 'TƯỚNG PHỦ ĐÍCH NỮ', 'Trầm Hoan', 'Tiên Hiệp, Đô Thị, Huyền Huyễn', 'Mang những tình tiết khôn khéo, lôi kéo độc giả đi từ \r\nbất ngờ này đến bất ngờ khác, truyện Tướng Phủ Đích Nữ là truyện xuyên không hiện đang được nhiều bạn \r\nđọc yêu mến. Với lối dẫn văn ngọt ngào của Trầm Hoan, truyện nói về nàng – Nạp \r\nLan Tĩnh, tướng phủ đích nữ đại tiểu thư, đệ nhất mỹ nữ kinh thành, một khi gả \r\nlàm thái tử phi lại tôn quý vô cùng.\r\n\r\nTrước nàng đoan trang cao quý,sau nàng tâm cơ đơn \r\nthuần,đem sói tin làm người tốt.\r\n\r\nNhưng khi thứ muội tiến cung, đã đánh mất vinh sủng của nàng, hại chết hoàng \r\nnhi, bức tử mẫu thân, bức điên huynh trưởng,hại một nhà ngoại tổ phụ bị diệt.', 'http://192.168.56.1:8080/doctruyen/anh/tuongphudichnuT9ipXaorbg.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia3.jpg', 2),
(12, 'TỔNG GIÁM ĐỐC, ĐỪNG TỚI ĐÂY!', 'Ăn quái thú', 'Ngôn Tình', '\"Nói đi, cô muốn bao nhiêu tiền, mới chịu rời khỏi con tôi?”\r\n\r\nTầng một nhà hàng Khải Toàn, một phụ nữ trung niên ăn mặc phú quý, ngồi ở góc cầu thang. Đối diện bà là một cô gái trẻ tuổi. Quần áo của cô gái này bình thường, bộ dạng lại xinh đẹp động lòng người. Mà lúc này, lại bởi vì câu nói của người phụ nữ trung niên, sắc mặt trở nên tái nhợt.\r\n\r\n\"Cháu...\" cô mở miệng nói.\r\n\r\n\"Được rồi! Tôi nghe nói, nhà cô khó khăn. Đây là 20 vạn, hẳn là đủ chứ!\"\r\n\"Bác, bác gái, cháu không hiểu ý của bác… Cháu, cháu muốn gặp Chu Hi! Cháu muốn nghe chính miệng anh ấy...\"\r\n\"Bác gái là lời cô có thể gọi à?\"\r\n\r\n\"Anh ấy nói anh ấy thích cháu, sẽ kết hôn với cháu...\"\r\n\r\n\"Kết hôn? Cô đúng là người si nói mộng!\" Người phụ nữ không khỏi nâng cao giọng: \"Cô cũng không soi gương, xem bản thân là thân phận gì! Chỉ dựa vào thân phận của cô, còn tính toán gả vào nhà họ Chu chúng tôi? Tôi nói cho cô biết, con tôi sắp đính hôn với Nhị tiểu thư nhà họ Vương rồi. Cô nên nhanh chóng cầm tờ chi phiếu này, biến mất trư.', 'http://192.168.56.1:8080/doctruyen/anh/tonggiamdocdungtoidayQhwnVcJpsu.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia2.jpg', 3),
(13, 'TÀ PHƯỢNG NGHỊCH THIÊN', 'Băng Y Khả Khả', 'Tiên Hiệp, Đô Thị, Huyền Huyễn', 'Tà Phượng Nghịch Thiên thuộc dị giới hay xoay \r\nquanh về Hạ Như Phong, dưỡng nữ của Hoa Hạ cổ võ thế gia, khi xuyên không qua \r\ntrở thành nữ nhi Nghiêm gia bị trục xuất khỏi Thiên Lang quốc.\r\n\r\nAi có thể nghĩ đến, tiểu thư yếu đuối sau một lần bị hãm hại, khi chết đi liền \r\nnghênh đón một cái linh hồn mới...\r\n\r\nXa bên kia thành thị, Hạ gia chính là nguyên nhân để nàng trở nên cường thế, dần \r\ndần tỏa sáng trong mắt mọi người trên đại lục.\r\n\r\nNgũ phẩm đan dược? Tính cái gì? Nàng hoàn toàn có thể xem là đường đậu ăn.\r\n\r\nNgươi có triệu hồi thú cấp bảy? Ngượng ngùng, thánh thú đều dẫn theo thuộc hạ đến \r\nchỗ nàng tìm nơi nương tựa.\r\n\r\nHối hận thì thế nào? Nhớ kỹ, trên đời này không có cách gì luyện chế thuốc hối \r\nhận.\r\n\r\nLong có nghịch lân, xúc giả tất phát.\r\n\r\nThương tổn đến nàng, chết!\r\n\r\nThương tổn đến Hạ gia, sống không bằng chết!\r\n', 'http://192.168.56.1:8080/doctruyen/anh/taphuongnghichthienr6nWyvqqYT.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia3.jpg', 3),
(14, 'SỐNG LẠI CƯNG VỢ NHƯ MẠNG', 'Thập Vĩ Thỏ (Thỏ mười đuôi)', 'Ngôn tình', 'Diệp Cửu Chiêu ngang ngược khó thuần phục trong miệng mọi người đã sống lại, đây là trở lại lúc Loan Loan vẫn còn sống sao?!\r\n\r\nMới vừa vào đại học, Loan Loan ngộ ra một chân lý, lời đồn là không thể tin!\r\nBằng không vì sao nghe nói nam thần Diệp cao cao tại thượng, ít khi nói cười lại dùng ánh mắt bức người nhìn mình hàng ngày chứ?\r\n\r\nĐây là chuyện về một vị nam thần không phải kẻ cặn bã.', 'http://192.168.56.1:8080/doctruyen/anh/songlaicungvonhumangkqQDkjuJIj.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia2.jpg', 3),
(15, 'KẾ THÊ', 'Hồ Thiên Bát Nguyệt', 'Kiếm hiệp', 'Tác giả Hồ Thiên Bát Nguyệt vừa cho ra đời siêu phẩmKế Thê, tác phẩm thuộc xuyên không sắc nói rằng năm nay mùa đông đặc biệt lạnh \r\nhơn mấy năm trước, nghe nói ở Yến Bắc đã chết cóng hơn mười người .\r\n\r\nMới từ trong ổ chăn ấm áp đi ra, Thường Nhuận Chi bị đông lạnh nhịn không được \r\nrun run.\r\n\r\nDiêu Hoàng đau lòng nói: \"Cô nương thân thể không tốt, mùa đông năm nay đã \r\ntrở bệnh vài lần. Thứ cho nô tì lắm miệng, cô nương sau này đừng vì việc này mà...\r\n', 'http://192.168.56.1:8080/doctruyen/anh/ketheSoTBu1mkq9.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia4.jpg', 3),
(18, 'QUẢ TÁO NHỎ', 'Nhược Thủy Thiên Lưu', 'Ngôn Tình, Võng Du, Truyện Teen, Sủng', 'Một câu chuyện tình yêu bước từ trong thế giới ảo những trò chơi game bước ra ngoài hiện thực.\r\n\r\nMọi chuyện bắt đầu từ lần đầu tiên Đóa Miên chơi PUBG, được ghép đội với một đệ nhất game thủ, danh xưng \"Quái thú châu Á\". Sau đó, cô lái xe không cẩn thận liền đâm chết anh ta. \r\n\r\nĐóa Miên: Thật sự xin lỗi! TT\r\n\r\nBroken: Lên giường nói sau.', 'http://192.168.56.1:8080/doctruyen/anh/qua-tao-nho.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 1),
(19, 'HÔN ƯỚC TUỔI 16!', 'Ravi', 'Hài Hước, Truyện Teen', 'Ngay từ khi chưa được sinh ra thì giữa họ đã được định sẵn hôn ước  từ đời ông cố để lại. Cũng từ đó mọi chuyện bắt đầu xảy ra khi hai con người   được gắn kết số phận  lại với nhau cùng bị cuốn vào  vòng xoáy của sự thù hận, những khúc mắc mà số phận nghiệt ngã đã cuốn lấy họ. Để rồi tình yêu sẽ hòa giải tất cả. Truyện cũng có chút hài hước. Mọi người theo dõi câu chuyện nhé.\r\n\r\nTruyện này mình đã viết được vài chương rồi, mỗi ngày mình sẽ ra một chương hoặc có thể hơn hoặc không tùy vào thời gian của mình nữa. Mong các bạn đón nhận. Chúc các bạn đọc truyện vui vẻ.\r\n\r\nGiới thiệu đôi chút về nhân vật cho các bạn nhé:\r\n\r\nNGUYỄN AN VY: 16t, tinh nghịch, đáng yêu, là con gái của 1 gia đình bình thường, cô không có điểm gì nổi bật ngoài tính quậy phá, có hôn ước với Khánh Anh\r\n\r\nVương Thái Điệp: 16t, tinh nghịch, dễ thương, là cô chủ của 1 tập đoàn lớn, có danh tiếng trong nước, là bạn thân của Khánh Anh và Bảo Nam, yêu Kin nhưng không thổ lộ, luôn đấu khẩu với Bảo Nam. Sau này là bạn thân của An Vy\r\n\r\nNGUYỄN HOÀNG KHÁNH ANH: 16t, đẹp trai, lạnh lùng, thông minh, học giỏi. là cậu chủ của 1 tập đoàn lớn có danh tiếng trong nước, là bạn thân của Thái Điệp và Bảo Nam. Có hôn ước với An Vy. Quậy phá, biết võ. \r\n\r\nTRẦN BẢO NAM: 16t, đẹp trai, ga lăng, thông minh, học giỏi, là cậu chủ của 1 tập đoàn lớn có danh tiếng. Là bạn thân của Khánh Anh và Thái Điệp, giỏi võ, có tình cảm với Thái Điệp nhưng không nói ra.\r\n\r\nTạm thời giới thiệu về 4 nhân vật chính đã, sau này xuất hiện các nhân vật sẽ giới thiệu sau.', 'http://192.168.56.1:8080/doctruyen/anh/hon-uoc-tuoi-16.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 1),
(20, 'BĂNG HẠ', 'vũ thu hiền', ' Truyện Teen', '\"Con đã chết đúng 10 năm\"\r\n\r\n\"Ngay trong vụ hỏa hoạn đó và giấy báo tử chính là điều chứng minh\"\r\n\r\n\"Con về đây không phải để mọi người biết con còn sống mà là tìm ra sự thật đằng sau vụ thảm họa đó\"\r\n\r\nMột sự thật đau lòng được che giấu đằng sau đó.\r\n\r\nMột kết thúc buồn thảm đã phủ nhận tất cả những cố gắng của họ để họ ra đi không thể nói một lời nào.\r\n\r\n\" Một vụ hỏa hoạn lớn đã xảy ra tại biệt thự họ Đoàn.... nguyên nhân vụ cháy đang có liên quan đến công chúa duy nhất gia tộc Đoàn\"\r\n\r\nEm: em sợ tình yêu của em không đủ lớn để giành cho anh vì em chỉ là đứa con của Quỷ Lửa\r\n\r\nAnh: đối với tôi, em là ngoại lệ.\r\n\r\nCuộc đời đều giống như trái bóng tròn vậy, nếu như ta không bị vấp ngã thì cũng sẽ chạy mãi như trái bóng không có điểm dừng.\r\n\r\nChẳng có nơi nào là đích và điểm tựa.\r\n\r\nNhưng rồi đến lúc cuối bóng cũng phải dừng và người cũng phải người. Đó là quy luật. Vòng quay cứ tiếp tục khi có người đá và có người giúp bạn đứng dậy.', 'http://192.168.56.1:8080/doctruyen/anh/bang-ha.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 1),
(21, 'SỔ TAY TRÙNG SINH', 'Lệ Ưu Đàm', ' Đô thị, Ngôn Tình, Xuyên Không', 'Kiếp trước, phải nói rằng cô vô cùng ngu ngốc. Rõ ràng rất thích anh, cuối cùng bản thân không biết cách thổ lộ, vì thế liền vuột mất anh, để lại cho bản thân một trái tim cô đơn trống trải. Điều này khiến cô hối hận tột cùng.\r\n\r\nTrước kia đã không nhận ra được tình cảm của bản thân, chính vì thế nên mới để vuột mất anh. Nhưng dường như ông trời cảm thương cho mối tình đơn phương của cô, liền cho Đồng Đồng cơ hội một lần nữa trọng sinh trở lại thời gian đẹp đẽ khi xưa. Lần này, cô quyết định sẽ thay đổi chính bản thân mình, sẽ không để cho người đàn ông vốn luôn nâng niu và săn sóc cô từng li từng tí trong lòng bàn tay khi cô còn bé vuột mất lần nữa.\r\n\r\n \r\n\r\n\r\nKhi còn là những đứa trẻ bé nhỏ đáng yêu chưa thể hiểu rõ sự đời, hai người bọn họ vốn là thanh mai trúc mã của nhau, cùng nhau lớn lên tại chính đại viện quân khu, cùng nhau vui đùa, ăn uống, nói chuyện, lấp đầy quá khứ bằng những hình ảnh đẹp đẽ chỉ có duy nhất hình bóng đối phương. Có lẽ chính vì thế, trong thâm tâm cô luôn mặc định cho rằng anh chính là người anh trai mà mình yêu quý, trân trọng và kính nể nhất. \r\n\r\nCô ngây thơ, hồn nhiên mà nghĩ vậy, nào hay rằng chính mình đang không ngừng tổn thương anh. Tình cảm sâu đậm của anh cũng phải đem chôn sâu xuống đáy lòng\r\n', 'http://192.168.56.1:8080/doctruyen/anh/sotaytrungsinha6Fp6GM3iy.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia3.jpg', 1),
(22, 'SỐNG LẠI LẦN NỮA Ở TẬN THẾ', 'Lâm Y Dương', 'Ngôn Tình, Xuyên Không', 'Sống Lại Lần Nữa Ở Tận Thế xoay quanh ánh tà \r\ndương đỏ như máu, chiếu rọi xác chết khắp nơi trên mặt đất, từng bầy zombie quần \r\náo tả tơi, bọn chúng nghe được mùi vị của máu tanh, cho dù gương mặt bị nghiền \r\nnát, nhưng vẫn có thể mơ hồ nhìn ra, bọn chúng hưng phấn và kích động.\r\n\r\nMùi hôi thối truyền tới trong không khí càng ngày \r\ncàng đậm, nồng nặc làm cho người khác buồn nôn, nhìn thấy càng ngày càng có nhiều \r\nzombie miệng phát ra những tiếng: “A. . .A. . .” chậm chạp tiến gần về phía...', 'http://192.168.56.1:8080/doctruyen/anh/songlailannuaotanthejeuZCJXVLD.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 1),
(23, 'PHÌ LŨ ĐẠI NÁO DỊ GIỚI', 'JunWei', ' Ngôn Tình, Dị Giới, Xuyên Không', 'Câu chuyện kể về một \"con heo mập\" đã vậy còn có tính hay tò mò  nên đã vì xem mưa sao băng, kết quả bị sao băng rơi trúng vào người kéo theo anh ta xuyên không tới dị giới. Với hệ thống trong tay, chúng ta cùng theo bước nhân vật chính ngông cuồng tung hoành đại náo dị giới.\r\n\r\nKhi đã đứng trên đỉnh điểm của đại lục Huyền Thiên, Dương Kiệt vẫn mang theo vẻ mặt sầu não nhìn về phía xa xăm, một tên tiểu đệ vô tình chứng kiến cảnh đó bền lên tiếng hỏi: \"Đại ca giờ đã là thiên hạ vô địch, mỹ nữ hậu cung đầy rẫy, quyền lực tiền bạc trở tay được ngay, sao còn mang vẻ sầu não thế này.\"\r\n\r\nDương Kiệt khẽ liếc nhìn tên tiểu đệ của mình một cái, đưa mắt nhìn về phía xa, thở dài nói: \"Sầu não duy nhất trong cuộc đời ta chính là cho tới thời điểm này vẫn chưa tìm được cách hút hết lớp mỡ dày trên cơ thể này để sở hữu thân hình sáu múi hoàn mỹ.\"', 'http://192.168.56.1:8080/doctruyen/anh/phi-lu-dai-nao-di-gioi.jpg', 'http://192.168.56.1:8080/doctruyen/anh/bia1.jpg', 2),
(24, 'THỢ SĂN TIỀN THƯỞNG', 'Kid1597', ' Trinh Thám, Truyện Teen', 'Chuyện xoay quanh anh chàng Hatake - một kẻ săn tiền thưởng khét tiếng ở một thành phố nhỏ của đất nước mặt trời mọc.\r\n\r\nAnh thường được cảnh sát giao cho nhiệm vụ truy tìm những tên tội phạm nguy hiểm và anh nhận được tiền thưởng cao nếu bắt sống được những kẻ đó.', 'http://192.168.56.1:8080/doctruyen/anh/tho-san-tien-thuong.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 2),
(25, 'EM MẶC CẢNH PHỤC RẤT ĐẸP', 'Quyên Ngô', 'Ngôn Tình, Truyện trinh thám', 'Tiếng còi xe cảnh sát hú còi inh ỏi vang vọng cả khu vực… Trong dòng xe đông đúc, có hai chiếc xe đang lao đi với tốc độ kinh hoàng… Chạy phía trước là một chiếc xe đen tối màu đang cố gắng lạng lách vượt qua những chiếc xe trước mặt, còn đuổi theo phía sau là một chiếc xe bình thường như bao chiếc xe khác màu bạc, nhưng khác biệt là trên nóc xe gắn thêm đèn hú tự động của cảnh sát!\r\n\r\nHai chiếc xe rượt đuổi sát sao làm cho đường phố trở nên hỗn loạn. Nhưng càng loạn hơn khi người trong chiếc xe phía trước không ngừng nã đạn vào vào chiếc xe cảnh sát phía sau… Nhưng dưới cơn mưa đạn, chiếc xe cảnh sát không hề bị trúng viên đại nào và cũng không ngừng lại mà chỉ kéo ra một khoảng cách xa hơn để tránh đạn.\r\n\r\n \r\n\r\n\r\nKhi ra khỏi đường cao tốc, đến một đoạn đường khá ít xe, chiếc xe cảnh sát phía sau bỗng nhiên tăng tốc, kéo gần hơn khoảng cách với xe phía trước.\r\n\r\nĐến một khoảng cách nhất định, từ bên trong xe cảnh sát bay ra một viên đạn và...rất chuẩn xác ghim vào bánh xe... Chiếc xe đang chạy với tốc độ cao bất ngờ bị bể bánh...mất lái...đâm thẳng vào lề đường... Sau đó thì văng trở ra...lộn ngược mấy vòng rồi dừng lại với bánh ngửa lên trời...\r\n\r\n \r\n\r\n\r\n', 'http://192.168.56.1:8080/doctruyen/anh/bossbadaoemmaccanhphucratdepTPFDIHEwQ8.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 2),
(26, 'PHIẾN ĐÁ NỞ RA HOA PHÙ TANG', 'Bạch Nhất Mặc', 'Ngôn Tình, Truyện trinh thám', 'Câu chuyện tình yêu giữa một vị đội trưởng vẻ ngoài nghiêm nghị lạnh lùng nhưng có một trái tim ấm áp. Anh được những người anh em trong cục yêu mến phong tặng anh biệt danh: Bàng tướng quân.\r\n\r\nNhưng bỗng một ngày hình ảnh \"Bàng tướng quân\" anh tuấn dũng mãnh của họ giáo huấn người khác đã không còn nữa mà là một anh chàng bị người phụ nữ bí ẩn lấy mất trái tim.', 'http://192.168.56.1:8080/doctruyen/anh/phiendanorahoaphutangeDc5mUVtii.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 2),
(27, 'ĐẾN EIFFEL VÀ CÙNG NÂNG LY CHA', 'Nouhaila Trang', 'Đô thị, Truyện trinh thám', 'Viêm Khải cùng Vivian - hai thiếu niên châu Á còn chưa tốt nghiệp cấp 3, đã cùng dắt nhau rời quê đến Pháp. Hai năm trôi qua, họ cùng khám phá thêm nhiều ngóc ngách sâu kín hơn của xã hội bằng việc trở thành thám tử.\r\n\r\n“Khải, Vivian. Chào mừng hai bạn chính thức gia nhập The Wolfr. Gọi tôi là Matthew. Chúng ta sẽ trao đổi bằng tiếng Anh. Tôi là một trong những quản lý của tổ thám tử, đồng thời là người liên lạc trực tiếp của hai bạn.”Viêm Khải và Vivian trao đổi những thông tin cơ bản với Matthew.“Tạm thời như vậy đã. Tôi cảm thấy rất tốt ở nhóm này. So với những đội đến từ châu Á khác, hai người rất chủ động. Các cậu còn câu hỏi gì không?”Vivian hiếu kỳ, “Những ký hiệu trên thiết bị chúng tôi nhận được là gì vậy? Có phải là logo của tổ chức không? Có ý nghĩa gì không? Sao lại phải “cắt” ra như vậy?”Matthew tròn mắt trước loạt câu hỏi của Vivian, có lẽ bình thường con bé này cũng hiếu kỳ với những gì diễn ra trong cuộc sống như vậy.“Hi hi, quan sát tốt lắm! Logo của tổ chức là ký hiệu vô cực với một đường kẻ nằm ngang, không phải bị cắt ra mà là được ghép vào bởi chữ M ở trên và W ở dưới. Hai chữ cái này là viết tắt của William E. và Marcel: là bí danh dùng để phân biệt chuyên môn của các thành viên.”Viêm Khải và Vivian đã hiểu. Hai người cùng tham gia chương trình huấn luyện cơ bản nhưng lại được đào tạo chuyên sâu với hai chương trình khác nhau. Đây là nhiệm vụ đầu tiên mà hai người nhận được sau bao nhiêu cố gắng, liệu họ có thể hoàn thành nó trôi chảy?', 'http://192.168.56.1:8080/doctruyen/anh/deneiffelvacungnanglychampagnei7E5SxRXcw.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 3),
(28, 'NỮ PHÁP Y MAU NHẢY VÀO TRONG B', 'Thuận Bảo Bảo', 'Ngôn Tình, Truyện trinh thám', 'Thi thể bé trai mặc y phục đỏ, thi thể nam giới dưới đáy giếng sâu, phần vụn tử thi nơi đồng không mông quạnh … Tăng Dĩ Nhu suốt ngày tiếp xúc với đủ hình đủ dạng thi thể đầy ghê rợn, vì lẽ đó cô hãnh diện trở thành một thành viên hội FA\r\n\r\n* Từ gốc ‘单身狗一枚 – Chú chó duy nhất: thường ám chỉ những người không có người yêu hoặc chưa kết hôn.\r\n\r\nTâm thần phân liệt, sát thủ biến thái, tâm lý vặn vẹo … Quanh năm suốt tháng Khúc Mịch say mê nghiên cứu đủ mọi loại hành vi, suy nghĩ lệch lạc; chính vì thế anh không những là ‘Team FA’ mà còn sắp trở thành thành viên lạc loài nhất trong hội FA.\r\n\r\nNữ Pháp Y đụng độ chuyên gia Tâm lý tội phạm …\r\n\r\nTăng Dĩ Nhu: Khúc Mịch là ‘Thi thể’ hoàn mỹ nhất mà cô từng gặp, bụng sáu múi hoàn hảo. Đối mặt với phần vụn thi thể mà vẫn có thể ung dung ăn miếng thịt gà, bình tĩnh, lạnh lùng … Tuyệt đối không phải là người bình thường.\r\n\r\nKhúc Mịch: Tăng Dĩ Nhu là một người phụ nữ biến thái mà xinh đẹp nhất mà anh từng gặp. Trông thấy thi thể hai mắt sáng rỡ, cầm dao giải phẫu tao nhã như đang thưởng thức món Âu, cô ấy đang hưởng thụ chiêm ngắm các tử thi bị lăng trì, thối rữa. Tuyệt đối không bình thường!', 'http://192.168.56.1:8080/doctruyen/anh/nuphapymaunhayvaotrongbat9usZUm9bgf.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 3),
(29, 'MẶT TRỜI MỌC TRONG BÓNG HOÀNG ', 'Mộc Tử Lãng', ' Ngôn Tình, Trinh Thám, Truyện Teen', 'Cuộc sống, không phải cứ muốn là được, cứ nuôi hy vọng là sẽ thành công. Tôi cũng muốn sống một cuộc sống tươi đẹp như bao người kia, cũng muốn đến bên cạnh, trò chuyện, hỏi han, chăm sóc cô gái ấy, cũng muốn được an nhàn đón một cái Tết đầy ý nghĩa bên gia đình và người thân,… Nhưng tất cả không như tôi muốn! Từ “ước mơ” hình như quá xa vời, mãi mãi không xuất hiện trong cuộc đời tôi…\r\n\r\n\r\nNgày ấy nắng nhạt, ánh mặt trời hắt lên vai tôi, nhưng trong lòng tôi có một cảm giác vô cùng khó chịu. Cô ấy đi rồi, đi thật rồi! Ước mơ bao nhiêu năm sống vì chính nghĩa của chúng tôi cuối cùng đổi được cái gì? Cô ấy hy sinh vì bắt tội phạm buôn bán trẻ em, cả đội cảnh sát chúng tôi thức trắng mấy đêm, cuối cùng trình toà chỉ ấm ức nghe câu “Chưa đủ chứng cứ, nghi phạm vô tội, phóng thích tại chỗ!”. Thật nực cười biết bao nhiêu, đúng không?', 'http://192.168.56.1:8080/doctruyen/anh/mat-troi-moc-trong-bong-hoang-hon.jpg', 'http://192.168.56.1:8080/doctruyen/anh/tieu-thuyet-tinh-yeu-3.jpg', 3),
(30, 'CHÁNH TÀ LƯỠNG ĐẠO', 'Tà Lão Quái (nguyễn nhạc)', 'iên Hiệp, Kiếm Hiệp, Dị Giới', 'Nội dung chính của câu chuyện xoay quanh giới tán tu nhiều điều không may mắn, là một người không có gia đình, mất cha lẫn mẹ, nhưng nhờ vào cơ duyên cuả bản thân, gã đã bước lên con đường đỉnh đạo. hắn tu liền chính lẫn tầm công pháp. đánh khắp thiên hạ vô địch thủ.\r\n', 'http://192.168.56.1:8080/doctruyen/anh/chanh-ta-luong-dao.jpg', 'http://192.168.56.1:8080/doctruyen/anh/anh3.jpg', 3),
(31, 'DẠ HÀNH CA', 'Tử Vi Lưu Niên', 'Kiếm Hiệp, Ngôn Tình, Cổ Đại', 'Thiếu niên hành tẩu, đâu ngờ lạc thiên sơn, sa vào trầm luân\r\nDung mạo thanh khiết, miết cái gió mây thay, bao kẻ kính sợ\r\nQuan ải vạn dặm lao đao, nào sợ chi phải quay đầu \r\nYêu quái hại người nhìn chẳng lạ, là mây mưa vần tự ắt định\r\nKhúc dạ hành ca, ta nghe cùng người\r\n', 'http://192.168.56.1:8080/doctruyen/anh/da-hanh-ca.jpg', 'http://192.168.56.1:8080/doctruyen/anh/anh3.jpg', 3);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `trangthai`
--

CREATE TABLE `trangthai` (
  `id_trangthai` int(11) NOT NULL,
  `ten_trangthai` varchar(30) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `trangthai`
--

INSERT INTO `trangthai` (`id_trangthai`, `ten_trangthai`) VALUES
(1, 'Mới'),
(2, 'Phổ biến'),
(3, 'Ưa thích');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `doctruyen`
--
ALTER TABLE `doctruyen`
  ADD PRIMARY KEY (`id_truyen`),
  ADD KEY `id_trangthai` (`id_trangthai`);

--
-- Chỉ mục cho bảng `trangthai`
--
ALTER TABLE `trangthai`
  ADD PRIMARY KEY (`id_trangthai`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `doctruyen`
--
ALTER TABLE `doctruyen`
  MODIFY `id_truyen` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=33;

--
-- AUTO_INCREMENT cho bảng `trangthai`
--
ALTER TABLE `trangthai`
  MODIFY `id_trangthai` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- Các ràng buộc cho các bảng đã đổ
--

--
-- Các ràng buộc cho bảng `doctruyen`
--
ALTER TABLE `doctruyen`
  ADD CONSTRAINT `doctruyen_ibfk_1` FOREIGN KEY (`id_trangthai`) REFERENCES `trangthai` (`id_trangthai`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
